-- CreateEnum
CREATE TYPE "BusinessType" AS ENUM ('ALIMENTATION_GENERALE', 'QUINCAILLERIE', 'BOUCHERIE', 'PRESSING', 'VETEMENT', 'TELEPHONE_ACCESSOIRES', 'ELECTROMENAGER', 'COSMETIQUE', 'SALON_COIFFURE', 'AUTRE');

-- AlterTable
ALTER TABLE "tenants" ADD COLUMN     "businessType" "BusinessType" NOT NULL DEFAULT 'ALIMENTATION_GENERALE';
